name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure
        run: >-
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DBUILD_TESTING=ON
          -DJGMD_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: cmake --build build --parallel 2

      - name: Test
        run: ctest --test-dir build --output-on-failure
